# pyproject.toml

[project]
dependencies = [
  "fastapi",
  "uvicorn",
  "pydantic",
  "pyjwt",
  "typing",
  "bcrypt",
  "psycopg2",
  "psycopg2-binary"
]
requires-python = ">=3.11"

[tool.mypy]
ignore_missing_imports = true
